### ISSUE TITLE
Why are there tsconfig.json and tsconfig.base.json alongside?

### ISSUE THREAD

**Issue by jjangga0214** [andrewthauer/ts-monorepo#2]
Why are there tsconfig.json and tsconfig.base.json alongside?

**Comment by MichaelGatesDev** [comment]
Although it makes no real difference here, it's likely that in a larger project that the `tsconfig.json` will have changes after extending `tsconfig.base.json`. That is my guess.

**Comment by andrewthauer** [comment]
Yes, basically. The `tsconfig.json` file is special in that most editor or language service based tooling will read this file by default to provide their IDE like experience for TypeScript. Splitting it out like this allows for more fine grained control for projects that require fine tuning per package, etc. That said, there's no rule saying it needs to be done this way. However, the usage of TS project references required a little bit of a different approach (see tsconfigs in the `packages` dir).
