### ISSUE TITLE
Using a better tool for the packaging process

### ISSUE THREAD

**Issue by zaguiini** [andrewthauer/ts-monorepo#3]
Isn't it possible to use a battle-tested tool to manage the environment configuration inside the packages? Something like [`tsdx`](https://github.com/jaredpalmer/tsdx)?

**Comment by andrewthauer** [comment]
Yes, anything should be possible. This repo was really just an experiment around the new TS project references feature to provide package boundaries while keeping a nice developer experience. I'd never heard of `tsdx` until now. Looks interesting, so I'll check it out. Thanks for sharing.
